# Generated by Django 5.2.14 on 2026-05-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('activity_value', models.FloatField()),
                ('activity_unit', models.CharField(max_length=50)),
                ('normalized_value', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField()),
                ('co2e_emission', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.datasource')),
            ],
        ),
    ]
